### ISSUE TITLE
Segmentation Violation on CSV

### ISSUE THREAD

**Issue by securesean** [lespea/smtpBrute#1]
![image](https://user-images.githubusercontent.com/10591609/83898557-b3760300-a71c-11ea-8d2b-d47ab10bd083.png)
[users.txt](https://github.com/lespea/smtpBrute/files/4737268/users.txt)

[findings.csv.txt](https://github.com/lespea/smtpBrute/files/4737271/findings.csv.txt)

**Comment by lespea** [comment]
Should be fixed now.  Pretty stupid of me :/
